# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apigeecli < Formula
  desc ""
  homepage "https://github.com/srinandan/apigeecli"
  version "1.100"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.100/apigeecli_v1.100_Darwin_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "5cbeec75c9468a79a70e7ea1c53cf47830e6560a682f274f737dabd92db20412"
    end
    if Hardware::CPU.arm?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.100/apigeecli_v1.100_Darwin_arm64.zip", :using => CurlDownloadStrategy
      sha256 "a08cdd3bc8274f896bc1055aff61fa452674941e628cae7fcc3778aab19684c1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.100/apigeecli_v1.100_Linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "db7fe48fa242419c509485f379c9dcdabc25f75307ab4945c857ba73afa10150"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.100/apigeecli_v1.100_Linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "abc57aafc4654050d0d6cc85e636e6a9ae07935292073074bce32003ab0784ab"
    end
  end

  def install
    bin.install "apigeecli"
  end
end
