# This file was generated by GoReleaser. DO NOT EDIT.
class Apigeecli < Formula
  desc ""
  homepage "https://github.com/srinandan/apigeecli"
  version "1.93"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/srinandan/apigeecli/releases/download/v1.93/apigeecli_v1.93_Darwin_x86_64.zip", :using => CurlDownloadStrategy
    sha256 "b30f2b26bdd2984ba14c687173cab992d0cbee7204a4e91266ca08dd1855f20b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.93/apigeecli_v1.93_Linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "162ea386c47043c098a52526b30518776c4801d39e93fe9c3f852e1b0cb2f33b"
    end
  end

  def install
    bin.install "apigeecli"
  end
end
