# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apigeecli < Formula
  desc ""
  homepage "https://github.com/srinandan/apigeecli"
  version "1.106-beta.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.106-beta.0/apigeecli_v1.106-beta.0_Darwin_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "fb7369e0ab7eefc822b866a5cd53309a0e226ef56e5ad685533433981cd742eb"

      def install
        bin.install "apigeecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.106-beta.0/apigeecli_v1.106-beta.0_Darwin_arm64.zip", :using => CurlDownloadStrategy
      sha256 "c0242ccbeaac97b0ba309c736e7b29da9a4b2f2c22f6385fc0c81732bf9aebf7"

      def install
        bin.install "apigeecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.106-beta.0/apigeecli_v1.106-beta.0_Linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "231cfa0ad893b9dc901e5693f64ec755ea9e422a6f920d4fe3d94b346c96bd61"

      def install
        bin.install "apigeecli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/srinandan/apigeecli/releases/download/v1.106-beta.0/apigeecli_v1.106-beta.0_Linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "18eb69f6f7e2ee4acca3fd883a9d4371d20cd982a0f8072d2151bd3bae3f1dd7"

      def install
        bin.install "apigeecli"
      end
    end
  end
end
